"""Hypothesis edge definitions for KG discovery."""

from datetime import datetime
from enum import Enum
from typing import Optional, Any
from pydantic import BaseModel, Field
import uuid

from .relations import RelationType


def generate_id() -> str:
    return str(uuid.uuid4())


class HypothesisStatus(str, Enum):
    """Status of a hypothesis edge."""
    PROPOSED = "proposed"  # Generated by system, not yet evaluated
    UNDER_EVALUATION = "under_evaluation"  # Currently being tested
    VALIDATED = "validated"  # Confirmed by evidence
    REJECTED = "rejected"  # Falsified by evidence
    INCONCLUSIVE = "inconclusive"  # Evidence neither confirms nor denies


class HypothesisSource(str, Enum):
    """How the hypothesis was generated."""
    KG_EMBEDDING = "kg_embedding"  # Link prediction from embeddings
    RULE_MINING = "rule_mining"  # Discovered via rule mining
    GNN_COMPLETION = "gnn_completion"  # GNN-based KG completion
    ABDUCTION = "abduction"  # Abductive reasoning
    HUMAN = "human"  # Human-proposed
    LLM = "llm"  # LLM-generated


class HypothesisEdge(BaseModel):
    """
    A hypothesized KG edge (typed relation) awaiting validation.

    This represents a candidate KG augmentation - a relationship that
    the system believes may be true but requires validation.
    """
    id: str = Field(default_factory=generate_id)

    # The hypothesized triple
    subject_id: str  # Entity ID (e.g., formulation, molecule)
    subject_type: str  # Entity type name
    relation: RelationType
    object_id: str  # Entity ID
    object_type: str  # Entity type name

    # Hypothesis metadata
    status: HypothesisStatus = HypothesisStatus.PROPOSED
    source: HypothesisSource
    confidence: float  # Model confidence (0-1)
    explanation: Optional[str] = None  # Human-readable explanation

    # Generation context
    generated_at: datetime = Field(default_factory=datetime.utcnow)
    model_name: Optional[str] = None  # e.g., "TransE", "ComplEx"
    model_version: Optional[str] = None
    generation_parameters: dict = Field(default_factory=dict)

    # Novelty checks
    is_novel: bool = True  # Not already in KG
    passed_time_slice: bool = False  # Passed time-slice filter
    cutoff_date: Optional[datetime] = None  # Time-slice cutoff used

    # Validation results
    validation_results: list[dict] = Field(default_factory=list)
    validated_at: Optional[datetime] = None
    validated_by: Optional[str] = None  # Agent/method that validated

    # If validated, track the predictive impact
    model_lift: Optional[float] = None  # Delta in model performance
    ablation_verified: bool = False  # Verified via ablation study

    # Evidence links
    supporting_evidence: list[str] = Field(default_factory=list)  # Source IDs
    contradicting_evidence: list[str] = Field(default_factory=list)

    def __hash__(self):
        return hash(self.id)

    def to_triple(self) -> tuple[str, str, str]:
        """Return as (subject, relation, object) triple."""
        return (self.subject_id, self.relation.value, self.object_id)

    def validate(
        self,
        status: HypothesisStatus,
        evidence: list[str],
        method: str,
        model_lift: Optional[float] = None,
    ) -> None:
        """Update hypothesis with validation results."""
        self.status = status
        self.validated_at = datetime.utcnow()
        self.validated_by = method
        self.model_lift = model_lift

        if status == HypothesisStatus.VALIDATED:
            self.supporting_evidence.extend(evidence)
        elif status == HypothesisStatus.REJECTED:
            self.contradicting_evidence.extend(evidence)

        self.validation_results.append({
            "status": status.value,
            "evidence": evidence,
            "method": method,
            "model_lift": model_lift,
            "timestamp": datetime.utcnow().isoformat(),
        })


class HypothesisBatch(BaseModel):
    """A batch of hypotheses generated together."""
    id: str = Field(default_factory=generate_id)
    hypotheses: list[HypothesisEdge] = Field(default_factory=list)
    generated_at: datetime = Field(default_factory=datetime.utcnow)
    source: HypothesisSource
    model_name: Optional[str] = None
    kg_version: str  # Version of KG used to generate
    num_proposed: int = 0
    num_novel: int = 0
    num_validated: int = 0
    num_rejected: int = 0

    def add_hypothesis(self, hypothesis: HypothesisEdge) -> None:
        """Add a hypothesis to the batch."""
        self.hypotheses.append(hypothesis)
        self.num_proposed += 1
        if hypothesis.is_novel:
            self.num_novel += 1

    def update_stats(self) -> None:
        """Update batch statistics."""
        self.num_proposed = len(self.hypotheses)
        self.num_novel = sum(1 for h in self.hypotheses if h.is_novel)
        self.num_validated = sum(
            1 for h in self.hypotheses if h.status == HypothesisStatus.VALIDATED
        )
        self.num_rejected = sum(
            1 for h in self.hypotheses if h.status == HypothesisStatus.REJECTED
        )
